from globals_.settings import settings
import os

if settings.ENVIRONMENT == 'prod':
    from .auth_prod import ProdAuth as Auth


BOT_TOKEN = os.environ['BOT_TOKEN']

FIREBASE_CONFIG = Auth.FIREBASE_CONFIG


RAPID_API_KEY = Auth.RAPID_API_KEY
MERRIAM_API_KEY = Auth.MERRIAM_API_KEY

SPOTIFY_CLIENT_ID = os.environ['SPOTIFY_CLIENT_ID']
SPOTIFY_CLIENT_SECRET = os.environ['SPOTIFY_CLIENT_SECRET']

GENIUS_ACCESS_TOKEN = Auth.GENIUS_ACCESS_TOKEN

MYANIMELIST_CLIENT_ID = Auth.MYANIMELIST_CLIENT_ID
